export interface AllEpData {
  all: number,
  buffer: number,
  active: number,
  active_not_ours: number,
  active_ours: number,
  active_zvp: number,
  active_property_realization: number,
  active_property_estate: number,
  active_queue_property: number,
  active_queue_real_estate: number,
  active_queue_auto: number,
  active_auction: number,
  active_previous_creditor: number,
  active_after_assignment: number,
  active_before_assignment: number,
  active_our_debtor: number,
  active_other: number,
  closed: number,
  closed_not_ours: number
  closed_ours: number,
  closed_zvp: number,
  closed_property_realization: number,
  closed_property_estate: number,
  closed_queue_property: number,
  closed_queue_real_estate: number,
  closed_queue_auto: number,
  closed_auction: number,
  closed_previous_creditor: number,
  closed_after_assignment: number,
  closed_before_assignment: number,
  closed_our_debtor: number,
  closed_other: number

}
